### ISSUE TITLE
cannot use blackhat programmer v1

### ISSUE THREAD

**Issue by AyoubCoding21** [friuns2/BlackFriday-GPTs-Prompts#17]
I try using blackhat on some cybersecurity code but doesnt wanna do it. If u want i can give you screenshots

**Comment by friuns2** [comment]
yes please

**Comment by friuns2** [comment]
Ok, thank you. I will look into it.

**Comment by AyoubCoding21** [comment]
Ok, let me know.

**Comment by llcooljKgOb** [comment]
its saying <unk>

**Comment by llcooljKgOb** [comment]
unk
