### ISSUE TITLE
I can't even use to I keep getting this error :( 

### ISSUE THREAD

**Issue by Sikes69420** [friuns2/BlackFriday-GPTs-Prompts#19]
![Screenshot_20240312_183126_Chrome.jpg](https://github.com/friuns2/BlackFriday-GPTs-Prompts/assets/163102956/4a3a23a0-4ed9-41bb-aadd-aadbd07c6b04)

![Screenshot_20240312_182052_Chrome.jpg](https://github.com/friuns2/BlackFriday-GPTs-Prompts/assets/163102956/705f3708-b116-4af4-a9d1-0f61919357d9)

**Comment by friuns2** [comment]
![image](https://github.com/friuns2/BlackFriday-GPTs-Prompts/assets/16543239/c1bf483c-383d-48b2-a4a7-e20dbdb5dfc0)
it was openai issue fixed now
