### ISSUE TITLE
I want you to remove my prompt from the page.

### ISSUE THREAD

**Issue by ForSasuke** [friuns2/BlackFriday-GPTs-Prompts#7]
I want you to remove my promo from this page. I made great efforts to make it, and for you to go and leak it means great disrespect for everyone's labour. You'll get nothing by doing this. Can you remove the WormGPT page in the Programming section?

**Comment by anhush8** [comment]
i didn't understand (

**Comment by anhush8** [comment]
is everything ok?

**Comment by anhush8** [comment]
I don't understand what I"ve done not correctly, pls help me correct it, i"m really sorry for inconvenience, i"ll do what I can, to resolve it.
